@apollo/explorer V1 & @apollo/sandbox V0 (#138)
* Build with rollup instead of tsdx (#123)

* use rollup instead of tsdx for building umd files.

* build cjs & esm with rollup. The build is going to look a litle different than before re: naming, but it achieves the same thing

* remove tsdx from repo

* remove unused test check

* npm ignore a bunch of files - we shouldn't need these in the npm package, right?

* isExplorer -> isSandbox and make the filenames more efficient

* export one function from createRollupConfig - let the config determine which helper to call

* add index.cjs file

* add babel

* remove unused dep fs-extra

* getting a an Error: cannot find module @babel/core, so lets try expliccitly installing it even though it should be a dep of @rollup/plugin-babel

* Split React export into its own file (#125)

* export react export from its own react folder

* specify second entry file as react/index.ts and write its own cjs entry point

* make react deps optional since react will be exported from its own file

* remove react export from index.ts

* transform sourcemaps since we flatten the src directory and rename node_modules

* rename ApolloExplorerReact component to ApolloExplorer now that it has its own file path

* modify Readme for ApolloExplorer React component exported from its own path and named ApolloExplorer not ApolloExplorerReact

* npm i to get updated package-lock

* NEBULA-1312 @apollo/sandbox package (#130)

* move explorer & sandbox into their own folders in side /packages

* move index.cjs & src/react/index.cjs into individual packages now

* Move /buildHelpers into explorer & sandbox packages, one for each

* setup package based tsconfig setup with a tsconfig in each package. Package tsconfigs extend base tsconfig with a different rootDir / outDir

* Setup workspace based package.json organization - one package.json for each package

* Edit build function so index files are written in the write place & new names of rollup configs are used

* setup sandbox package with react & js export

* add react example to sandbox package as well

* Add README & LICENSE to each package & edit to be package specific

* update circle ci config for new file paths

* add codesandbox config to support a sandbox & explorer deploy preview

* update github workflow for new file paths

* add a command to build all packages cjs / esm

* fix pathnames of local dev examples

* cherry pick changes on main -> all cjs - esm build works

* typescript check doesn't work with composites - just base tsconfig for build

* try to get typings to work

* make endpointUrl only required when schema is passed DON'T RELEASE UNTIL STUDIO PR IS OUT FOR A WHILE (#135)

* make endpointUrl only required when schema is passed, otherwise it is not allowed to be passed with graphRef - we will use the endpoint from your graph

* support older version of studio webapp

* modify types for react component

* remove source maps for now - we dont build the chunks for each individual file

* add publish prepare script that builds, and removes all files except the dist files at the root for publish

* cleanup automated ci jobs & code sandbox build command - no functional changes

* remove unused changeset npm script since now we publish from root

* don't minimize production build so folks can use it as a sourcemap

* changeset