Build with rollup instead of tsdx (#123)
* use rollup instead of tsdx for building umd files.

* build cjs & esm with rollup. The build is going to look a litle different than before re: naming, but it achieves the same thing

* remove tsdx from repo

* remove unused test check

* npm ignore a bunch of files - we shouldn't need these in the npm package, right?

* isExplorer -> isSandbox and make the filenames more efficient

* export one function from createRollupConfig - let the config determine which helper to call

* add index.cjs file

* add babel

* remove unused dep fs-extra

* getting a an Error: cannot find module @babel/core, so lets try expliccitly installing it even though it should be a dep of @rollup/plugin-babel